public class BVCacrMonthlyReportScheduleEshipHelper {
   
@InvocableMethod
    public static void acrschedulerByUser(){
        
      
        System.schedule('BVCacrMonthlyReportScheduleEship 13', '0 03 * * * ?', new BVCacrMonthlyReportScheduleEship());
        System.schedule('BVCacrMonthlyReportScheduleEship 14', '0 07 * * * ?', new BVCacrMonthlyReportScheduleEship());
        System.schedule('BVCacrMonthlyReportScheduleEship 15', '0 13 * * * ?', new BVCacrMonthlyReportScheduleEship());
        System.schedule('BVCacrMonthlyReportScheduleEship 16', '0 17 * * * ?', new BVCacrMonthlyReportScheduleEship());
        System.schedule('BVCacrMonthlyReportScheduleEship 17', '0 23 * * * ?', new BVCacrMonthlyReportScheduleEship());
        System.schedule('BVCacrMonthlyReportScheduleEship 18', '0 27 * * * ?', new BVCacrMonthlyReportScheduleEship());
        System.schedule('BVCacrMonthlyReportScheduleEship 19', '0 33 * * * ?', new BVCacrMonthlyReportScheduleEship());
        System.schedule('BVCacrMonthlyReportScheduleEship 20', '0 37 * * * ?', new BVCacrMonthlyReportScheduleEship());
        System.schedule('BVCacrMonthlyReportScheduleEship 21', '0 43 * * * ?', new BVCacrMonthlyReportScheduleEship());
        System.schedule('BVCacrMonthlyReportScheduleEship 22', '0 47 * * * ?', new BVCacrMonthlyReportScheduleEship());
        System.schedule('BVCacrMonthlyReportScheduleEship 23', '0 53 * * * ?', new BVCacrMonthlyReportScheduleEship());
        System.schedule('BVCacrMonthlyReportScheduleEship 24', '0 57 * * * ?', new BVCacrMonthlyReportScheduleEship());
        System.schedule('BVCacrMonthlyReportScheduleEship 1', '0 05 * * * ?', new BVCacrMonthlyReportScheduleEship());
        System.schedule('BVCacrMonthlyReportScheduleEship 2', '0 10 * * * ?', new BVCacrMonthlyReportScheduleEship());
        System.schedule('BVCacrMonthlyReportScheduleEship 3', '0 15 * * * ?', new BVCacrMonthlyReportScheduleEship());
        System.schedule('BVCacrMonthlyReportScheduleEship 4', '0 20 * * * ?', new BVCacrMonthlyReportScheduleEship());
        System.schedule('BVCacrMonthlyReportScheduleEship 5', '0 25 * * * ?', new BVCacrMonthlyReportScheduleEship());
        System.schedule('BVCacrMonthlyReportScheduleEship 6', '0 30 * * * ?', new BVCacrMonthlyReportScheduleEship());
        System.schedule('BVCacrMonthlyReportScheduleEship 7', '0 35 * * * ?', new BVCacrMonthlyReportScheduleEship());
        System.schedule('BVCacrMonthlyReportScheduleEship 8', '0 40 * * * ?', new BVCacrMonthlyReportScheduleEship());
        System.schedule('BVCacrMonthlyReportScheduleEship 9', '0 45 * * * ?', new BVCacrMonthlyReportScheduleEship());
        System.schedule('BVCacrMonthlyReportScheduleEship 10', '0 50 * * * ?', new BVCacrMonthlyReportScheduleEship());
        System.schedule('BVCacrMonthlyReportScheduleEship 11', '0 55 * * * ?', new BVCacrMonthlyReportScheduleEship());
        System.schedule('BVCacrMonthlyReportScheduleEship 12', '0 00 * * * ?', new BVCacrMonthlyReportScheduleEship());
        System.schedule('BVCacrMontlyEmailsScheduleEship 13', '0 03 * * * ?', new BVCacrMontlyEmailsScheduleEship());
        System.schedule('BVCacrMontlyEmailsScheduleEship 14', '0 07 * * * ?', new BVCacrMontlyEmailsScheduleEship());
        System.schedule('BVCacrMontlyEmailsScheduleEship 15', '0 13 * * * ?', new BVCacrMontlyEmailsScheduleEship());
        System.schedule('BVCacrMontlyEmailsScheduleEship 16', '0 17 * * * ?', new BVCacrMontlyEmailsScheduleEship());
        System.schedule('BVCacrMontlyEmailsScheduleEship 17', '0 23 * * * ?', new BVCacrMontlyEmailsScheduleEship());
        System.schedule('BVCacrMontlyEmailsScheduleEship 18', '0 27 * * * ?', new BVCacrMontlyEmailsScheduleEship());
        System.schedule('BVCacrMontlyEmailsScheduleEship 19', '0 33 * * * ?', new BVCacrMontlyEmailsScheduleEship());
        System.schedule('BVCacrMontlyEmailsScheduleEship 20', '0 37 * * * ?', new BVCacrMontlyEmailsScheduleEship());
        System.schedule('BVCacrMontlyEmailsScheduleEship 21', '0 43 * * * ?', new BVCacrMontlyEmailsScheduleEship());
        System.schedule('BVCacrMontlyEmailsScheduleEship 22', '0 47 * * * ?', new BVCacrMontlyEmailsScheduleEship());
        System.schedule('BVCacrMontlyEmailsScheduleEship 23', '0 53 * * * ?', new BVCacrMontlyEmailsScheduleEship());
        System.schedule('BVCacrMontlyEmailsScheduleEship 24', '0 57 * * * ?', new BVCacrMontlyEmailsScheduleEship());
        System.schedule('BVCacrMontlyEmailsScheduleEship 1', '0 05 * * * ?', new BVCacrMontlyEmailsScheduleEship());
        System.schedule('BVCacrMontlyEmailsScheduleEship 2', '0 10 * * * ?', new BVCacrMontlyEmailsScheduleEship());
        System.schedule('BVCacrMontlyEmailsScheduleEship 3', '0 15 * * * ?', new BVCacrMontlyEmailsScheduleEship());
        System.schedule('BVCacrMontlyEmailsScheduleEship 4', '0 20 * * * ?', new BVCacrMontlyEmailsScheduleEship());
        System.schedule('BVCacrMontlyEmailsScheduleEship 5', '0 25 * * * ?', new BVCacrMontlyEmailsScheduleEship());
        System.schedule('BVCacrMontlyEmailsScheduleEship 6', '0 30 * * * ?', new BVCacrMontlyEmailsScheduleEship());
        System.schedule('BVCacrMontlyEmailsScheduleEship 7', '0 35 * * * ?', new BVCacrMontlyEmailsScheduleEship());
        System.schedule('BVCacrMontlyEmailsScheduleEship 8', '0 40 * * * ?', new BVCacrMontlyEmailsScheduleEship());
        System.schedule('BVCacrMontlyEmailsScheduleEship 9', '0 45 * * * ?', new BVCacrMontlyEmailsScheduleEship());
        System.schedule('BVCacrMontlyEmailsScheduleEship 10', '0 50 * * * ?', new BVCacrMontlyEmailsScheduleEship());
        System.schedule('BVCacrMontlyEmailsScheduleEship 11', '0 55 * * * ?', new BVCacrMontlyEmailsScheduleEship());
        System.schedule('BVCacrMontlyEmailsScheduleEship 12', '0 00 * * * ?', new BVCacrMontlyEmailsScheduleEship());  
        

    }
 
    public static void acrmonthlyhealper() {
        IF(datetime.now().hour() == 23 && datetime.now().minute() == 30) {
            for (CronTrigger job: [select Id, CronJobDetail.Name from CronTrigger where CronJobDetail.JobType = '7'
                    and (CronJobDetail.Name like '%BVCacrMonthlyReportScheduleEship%' or CronJobDetail.Name like '%BVCacrMontlyEmailsScheduleEship%')
                ]) {
                System.abortJob(job.Id);
                System.debug('cancellation path');
            }
        }

    }

}