public class CreditNoteTriggerHandler {
    public static void dummyMethod(){
      integer i = 0;
        
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;

        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;

        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;  
    }}
    
 /*  
    public static final map<String,String> mapOfTypeCode = new map<String,String>{
        'Tax Invoice' => 'T', 'Bill of Supply Invoice' => 'B',
            'Commercial Invoice ' => 'C', 'Tax Credit Note' => 'T',
            'Bill of Supply Credit Note' => 'B', 'Commercial Credit Note' => 'C'
    } ;
    
        
    
                
    /**
     *  Name : amountsInWordConversion
     *  Description : Convert. Total Amount To word for Document
     *  Param : Trigger.new and Old map
     *  Return : None
     * 
    *   
    
    public static void amountsInWordConversion(List<blng__CreditNote__c> newList,Map<Id,blng__CreditNote__c> oldMap){
        NumberTOWordConvertion numtoword = new NumberTOWordConvertion ();
        for(blng__CreditNote__c cnRec : newList){
            if(cnRec.blng__TotalAmount__c != null && cnRec.blng__TotalAmount__c >=0 && cnRec.blng__TotalAmount__c != oldMap.get(cnRec.Id).blng__TotalAmount__c){
                cnRec.Total_Amount_In_Words__c = numtoword.getNumberTOWordConvertion(cnRec.blng__TotalAmount__c);
            }
        }                
    }    
   public static void updateRecordType(List<blng__CreditNote__c> newList){
        set<Id> invoiceIds = new set<Id>();
        for(blng__CreditNote__c cn:newList){
            if(cn.blng__RelatedInvoice__c!=null)
            invoiceIds.add(cn.blng__RelatedInvoice__c);    
        }
        map<Id, blng__Invoice__c> mapInvoice=new map<Id,blng__Invoice__c>([select id, BVC_CB_Invoice_Type__c from blng__Invoice__c where Id in:invoiceIds]);
        //Tax Invoice, Commercial Invoice , Bill of Supply Invoice
         
        map<String, Id> mapRecordType = new map<String, Id>();
        product2 cbprod=[select id,name from product2 where name='CUSTOM BROKERAGE'];
        for(recordtype r:[select Id,DeveloperName from RecordType where SobjectType ='blng__CreditNote__c']){
        mapRecordType.put(r.DeveloperName,r.Id);    
        }
        for(blng__CreditNote__c cn:newList){
            String developerName = 'Master';
            String creditnotetype = 'Tax Credit Note';
            if(mapInvoice.get(cn.blng__RelatedInvoice__c).BVC_CB_Invoice_Type__c=='Tax Invoice')
            {
                developerName='Tax_Credit_Note';
                cn.product__c=cbprod.id;
            }
            if(mapInvoice.get(cn.blng__RelatedInvoice__c).BVC_CB_Invoice_Type__c=='Commercial Invoice'){
             	developerName='Commercial_Credit_Note';
                creditnotetype = 'Commercial Credit Note'; 
                cn.product__c=cbprod.id;
            }
            if(mapInvoice.get(cn.blng__RelatedInvoice__c).BVC_CB_Invoice_Type__c=='Bill of Supply Invoice')
            {
                developerName='BOS_Credit_Note';
                creditnotetype = 'Bill of Supply Credit Note';
                cn.product__c=cbprod.id;
            }
            	
            cn.RecordTypeId = mapRecordType.get(developerName); 
			cn.Credit_Note_Type__c = creditnotetype;            
        }
    }
    /*
     * Name : updateEmailRecepients
     * Description : Update the Email Recepients
     * Param : Trigger.new
     * Return : None
     * 
     
    
    public static void updateEmailRecepients(List<blng__CreditNote__c> newList){
        Set<Id> accountIds = new Set<Id>();
        Set<Id> invoiceIds = new Set<Id>();
        Set<Id> dealIds = new Set<Id>();
        Map<Id,String> mapAccountRecepients = new Map<Id,String>();
        Map<Id,blng__Invoice__c> mapInvoice = new Map<Id,blng__Invoice__c>();
        Map<Id,String> mapDealRecepients = new Map<Id,String>();
        
        for(blng__CreditNote__c cnRec : newList){
            accountIds.add(cnRec.blng__Account__c);
            invoiceIds.add(cnRec.blng__RelatedInvoice__c);
        }
        System.debug('accountIds. '+accountIds);
        System.debug('invoiceIds. '+invoiceIds);
        for(AccountContactRelation acr : [select AccountId,ContactId,Roles,Contact.Email from AccountContactRelation where Roles INCLUDES ('Invoice Recepient;Finance') AND AccountId in:accountIds AND Contact.Email != null ]){
            if(mapAccountRecepients.containsKey(acr.AccountId)){
                String recepientStr = mapAccountRecepients.get(acr.AccountId);
                recepientStr = recepientStr + ', '+ acr.Contact.Email;
                mapAccountRecepients.put(acr.AccountId, recepientStr);
            }else {
                mapAccountRecepients.put(acr.AccountId,acr.Contact.Email);
            }
        }
        System.debug('mapAccountRecepients. '+mapAccountRecepients);
        for(blng__Invoice__c inv : [Select id,blng__Order__c,blng__Order__r.OpportunityId,blng__Order__r.Business_Type__c from blng__Invoice__c where id in:invoiceIds AND blng__Order__r.Business_Type__c ='ACR']){
            if(inv.blng__Order__c != null && inv.blng__Order__r.OpportunityId != null){
                dealIds.add(inv.blng__Order__r.OpportunityId);
                mapInvoice.put(inv.Id, inv);
            }
        }
        System.debug('mapInvoice. '+mapInvoice);
        System.debug('dealIds. '+dealIds);
        List<String> strRole = new List<String>();
        strRole.add('Decision Maker');
        strRole.add('Evaluator');
        for(OpportunityContactRole oppRole : [SELECT ContactId,Id,IsPrimary,OpportunityId,Role,Contact.Email FROM OpportunityContactRole WHERE OpportunityId in : dealIds AND Role IN:strRole AND Contact.Email != null]){
            System.debug('oppRole. '+oppRole);
            if(mapDealRecepients.containsKey(oppRole.OpportunityId)){
                String recepientStr = mapDealRecepients.get(oppRole.OpportunityId);
                recepientStr = recepientStr + ', '+ oppRole.Contact.Email;
                mapDealRecepients.put(oppRole.OpportunityId, recepientStr);
            }else {
                mapDealRecepients.put(oppRole.OpportunityId, oppRole.Contact.Email);
            }
        }
        System.debug('mapDealRecepients. '+mapDealRecepients);
        for(blng__CreditNote__c cnRec : newList){
            if( cnRec.blng__RelatedInvoice__c != null && mapInvoice.containsKey(cnRec.blng__RelatedInvoice__c)){
                cnRec.Email_Recepients__c = (mapDealRecepients.containsKey(mapInvoice.get(cnRec.blng__RelatedInvoice__c).blng__Order__r.OpportunityId) ? mapDealRecepients.get(mapInvoice.get(cnRec.blng__RelatedInvoice__c).blng__Order__r.OpportunityId) :'');
            }
            else if(mapAccountRecepients.containsKey(cnRec.blng__Account__c)){
                cnRec.Email_Recepients__c = mapAccountRecepients.get(cnRec.blng__Account__c);
            }
        }
       
    }
    
        
    
    /**
    * Method Name : gstSerialNumberUpdate
    * Description : Update Invoice Serial Number based on GST
    * Param : Trigger.new
    * 
    
    
    public static void gstSerialNumberUpdate(List<blng__CreditNote__c> newList){
        system.debug('Inside gstSerialNumberUpdate=========');
        Map<Id,String> orderIds=new map<Id,String>();
        Map<Id,blng__CreditNote__c> cbcreditnotes = new Map<Id,blng__CreditNote__c>();
        map<String, Id> mapRecordType = new map<String, Id>();
        String Masterid;
        Boolean hastaxcn = false;
        Boolean hasBOScn = false;
        Boolean hasCommcn = false;
        for(recordtype r:[select Id,DeveloperName from RecordType where SobjectType ='blng__CreditNote__c']){
            system.debug('r.developer name ===='+r.DeveloperName);
            if(r.DeveloperName == 'Master'){
                Masterid = r.id;
            }    
        }
        for(blng__CreditNote__c cnRec: newList){
            if( cnRec.Credit_Note_Type__c != null 
             && cnRec.Approval_Status__c == 'Approved'
             && (cnRec.CreditNote_Serial_No__c == null || String.isBlank(cnRec.CreditNote_Serial_No__c))){
                 system.debug('Inside 1st If=====');
                 system.debug('cnRec.RecordTypeId====='+cnRec.RecordTypeId);
                 if(cnRec.RecordTypeId != Masterid){
                     cbcreditnotes.put(cnRec.blng__RelatedInvoice__c, cnRec);
                     if(cnRec.Credit_Note_Type__c =='Tax Credit Note')hastaxcn =true;
                     if(cnRec.Credit_Note_Type__c =='Bill of Supply Credit Note')hasBOScn =true;
                     if(cnRec.Credit_Note_Type__c =='Commercial Credit Note')hasCommcn=true;
                 }
                 
                 else{
                     orderIds.put(cnRec.blng__RelatedInvoice__c, cnRec.Credit_Note_Type__c );
                 }                
            }
        }
        system.debug('hastaxcn=='+hastaxcn);
                 system.debug('hasBOScn=='+hasBOScn);
                 system.debug('hasCommcn=='+hasCommcn);
        if(cbcreditnotes.size()>0){
          /*  list<blng__CreditNote__c> Taxcn = new list<blng__CreditNote__c>();
            list<blng__CreditNote__c> Boscn = new list<blng__CreditNote__c>();
            list<blng__CreditNote__c> Commcn = new list<blng__CreditNote__c>();
            if(hastaxcn) Taxcn= [select id from blng__CreditNote__c where Credit_Note_Type__c = 'Tax Credit Note' and CreditNote_Serial_No__c != null and RecordType.name !=null];
            if(hasBOScn) Boscn = [select id from blng__CreditNote__c where Credit_Note_Type__c = 'Bill of Supply Credit Note'and CreditNote_Serial_No__c != null];
            if(hasCommcn) Commcn = [select id from blng__CreditNote__c where Credit_Note_Type__c = 'Commercial Credit Note'and CreditNote_Serial_No__c != null];
          	integer taxcncount=Taxcn.size()+1;
            integer Boscncount=Boscn.size()+1;
            integer Commcncount=Commcn.size()+1; //code for exiting blng credit note
            
            
            list<blng__CreditNote__c> TaxcnOld = new list<blng__CreditNote__c>();
            list<blng__CreditNote__c> BoscnOld = new list<blng__CreditNote__c>();
            list<blng__CreditNote__c> CommcnOld = new list<blng__CreditNote__c>();
            list<BVCCreditNote__c> Taxcn = new list<BVCCreditNote__c>();
            list<BVCCreditNote__c> Boscn = new list<BVCCreditNote__c>();
            list<BVCCreditNote__c> Commcn = new list<BVCCreditNote__c>();
            
            if(hastaxcn) Taxcn= [select id from BVCCreditNote__c where Credit_Note_Type__c = 'Tax Credit Note' and CreditNote_Serial_No__c != null and RecordType.name !=null];
            if(hasBOScn) Boscn = [select id from BVCCreditNote__c where Credit_Note_Type__c = 'Bill of Supply Credit Note'and CreditNote_Serial_No__c != null];
            if(hasCommcn) Commcn = [select id from BVCCreditNote__c where Credit_Note_Type__c = 'Commercial Credit Note'and CreditNote_Serial_No__c != null];
            if(hastaxcn) TaxcnOld= [select id from blng__CreditNote__c where Credit_Note_Type__c = 'Tax Credit Note' and CreditNote_Serial_No__c != null and RecordType.name !=null];
            if(hasBOScn) BoscnOld = [select id from blng__CreditNote__c where Credit_Note_Type__c = 'Bill of Supply Credit Note'and CreditNote_Serial_No__c != null];
            if(hasCommcn) CommcnOld = [select id from blng__CreditNote__c where Credit_Note_Type__c = 'Commercial Credit Note'and CreditNote_Serial_No__c != null];
            
            system.debug('Taxcn.size()+TaxcnOld.size()========'+Taxcn.size()+TaxcnOld.size());
            integer taxcncount=Taxcn.size()+TaxcnOld.size()+1;
            integer Boscncount=Boscn.size()+BoscnOld.size()+1;
            integer Commcncount=Commcn.size()+CommcnOld.size()+1;
             system.debug('taxcncount========'+taxcncount);
            for(blng__CreditNote__c cr:newList){
                if(cr.RecordTypeId != Masterid){
                    if(cr.Credit_Note_Type__c == 'Tax Credit Note'){
                        string ser1= cr.Invoice_Series__c.SubStringBefore('I')+'C'+String.valueOf(taxcncount);
                        cr.CreditNote_Serial_No__c = ser1;
                        taxcncount++;
                    }
                    if(cr.Credit_Note_Type__c == 'Bill of Supply Credit Note'){
                        string ser1= cr.Invoice_Series__c.SubStringBefore('I')+'C'+String.valueOf(Boscncount);
                        cr.CreditNote_Serial_No__c = ser1;
                        Boscncount++;
                    }
                    if(cr.Credit_Note_Type__c == 'Commercial Credit Note'){
                        string ser1= cr.Invoice_Series__c.SubStringBefore('I')+'C'+String.valueOf(Commcncount);
                        cr.CreditNote_Serial_No__c = ser1;
                        Commcncount++;
                    }
                }
            }
        }
      
        Map<Id,String> orderMap = new Map<Id,String>();
        if(orderIds != null && orderIds.size() >0){
            orderMap = getBranchinfo(orderIds);
        }
        Map<String,Integer> mapUniqueKeyNumber = new Map<String,Integer>();
        List<DocumentSeries__c>upsertList = new List<DocumentSeries__c>();
        Map<String,DocumentSeries__c> mapUniqueKeyRecord =new Map<String,DocumentSeries__c>();
        if(orderMap != null){
            for(DocumentSeries__c doc : [Select Unique_Key__c, Last_Serial_Number__c from DocumentSeries__c where Unique_Key__c IN:orderMap.values()]){
                mapUniqueKeyNumber.put(doc.Unique_Key__c,Integer.valueOf(doc.Last_Serial_Number__c.right(doc.Last_Serial_Number__c.length() - doc.Unique_Key__c.length())));
                mapUniqueKeyRecord.put(doc.Unique_Key__c,doc);
            }
            for(blng__CreditNote__c cnRec: newList){
                if(cnRec.CreditNote_Serial_No__c == null || String.isBlank(cnRec.CreditNote_Serial_No__c)){
                    if(orderMap != null && orderMap.containsKey(cnRec.blng__RelatedInvoice__c)){
                        if(mapUniqueKeyNumber.containsKey(orderMap.get(cnRec.blng__RelatedInvoice__c))){
                            Integer newSerialNUmber = mapUniqueKeyNumber.get(orderMap.get(cnRec.blng__RelatedInvoice__c)) +1;
                            cnRec.CreditNote_Serial_No__c = orderMap.get(cnRec.blng__RelatedInvoice__c) + newSerialNUmber;
                            mapUniqueKeyRecord.get(orderMap.get(cnRec.blng__RelatedInvoice__c)).Last_Serial_Number__c = orderMap.get(cnRec.blng__RelatedInvoice__c) + newSerialNUmber;
                            mapUniqueKeyNumber.put(orderMap.get(cnRec.blng__RelatedInvoice__c),newSerialNUmber);
                            
                        }else{
                            cnRec.CreditNote_Serial_No__c = orderMap.get(cnRec.blng__RelatedInvoice__c) + 1;
                            DocumentSeries__c docM = new DocumentSeries__c();
                            docM.Name = orderMap.get(cnRec.blng__RelatedInvoice__c);
                            docM.Last_Serial_Number__c = orderMap.get(cnRec.blng__RelatedInvoice__c) + 1;
                            docM.Unique_Key__c = orderMap.get(cnRec.blng__RelatedInvoice__c);
                            mapUniqueKeyRecord.put(orderMap.get(cnRec.blng__RelatedInvoice__c),docM);
                            mapUniqueKeyNumber.put(orderMap.get(cnRec.blng__RelatedInvoice__c),1);
                        }
                    }
                }
            }
            
            upsert mapUniqueKeyRecord.values();
        }
        
    }
    
    /**
    * Method Name : getBranchInfo
    * Description : get The related Branch info W.R.T Order
    * Param : List of Order ids
    * Return : Map<Id, OrderObect>
    *
    
    
    public static Map<Id,String> getBranchInfo(Map<Id,String> orderMap){
        Map<Id,String> mapOrderKey = new map<Id,String>();
        for ( blng__Invoice__c inv : [Select id,BVC_Branch__r.ST_BVC_Billing_Entity__r.Billing_Serial_Number__c,BVC_Branch__r.ST_BVC_Billing_Entity__r.GSTIN_State_Code__c from blng__Invoice__c 
                                where BVC_Branch__c != null AND BVC_Branch__r.ST_BVC_Billing_Entity__c != null  AND
                                BVC_Branch__r.ST_BVC_Billing_Entity__r.GSTIN_State_Code__c != null AND Id IN :orderMap.keyset()] )
        {
            String serialNumber = (inv.BVC_Branch__r.ST_BVC_Billing_Entity__r.Billing_Serial_Number__c != null?String.valueOf(inv.BVC_Branch__r.ST_BVC_Billing_Entity__r.Billing_Serial_Number__c) :'01');
            String serialNumberUniqueCode = inv.BVC_Branch__r.ST_BVC_Billing_Entity__r.GSTIN_State_Code__c + mapOfTypeCode.get(orderMap.get(inv.Id)) + 'C' + serialNumber;
            mapOrderKey.put(inv.Id, serialNumberUniqueCode);
        }
        return mapOrderKey;
    }
    public static void callEYTaxCal(List<blng__CreditNote__c> newList, Map<Id,blng__CreditNote__C> oldMap){
        Map<Id, RecordType> mapRecordType = new Map<Id, RecordType>([select Id,DeveloperName from RecordType where SobjectType ='blng__CreditNote__c']);
        List<blng__CreditNote__c> otherCNList = new List<blng__CreditNote__c>(); 
        for(blng__CreditNote__c cnRec : newList){
                
                if( mapRecordType.get(cnRec.RecordTypeId)!=null && (mapRecordType.get(cnRec.RecordTypeId).DeveloperName=='BOS_Credit_Note' || mapRecordType.get(cnRec.RecordTypeId).DeveloperName=='Tax_Credit_Note') && cnRec.Approval_Status__c == 'Approved' && cnRec.Approval_Status__c != oldMap.get(cnRec.Id).Approval_Status__c){
                	//CPQ_CNEYTaxCalculation taxHandler = new CPQ_CNEYTaxCalculation();
                    CPQ_CNEYTaxCalculation.doTaxCalculationForCN(cnRec.Id);
                }
                if( mapRecordType.get(cnRec.RecordTypeId)!=null && mapRecordType.get(cnRec.RecordTypeId).DeveloperName=='Commercial_Credit_Note'&& cnRec.Approval_Status__c == 'Approved' && cnRec.Approval_Status__c != oldMap.get(cnRec.Id).Approval_Status__c){
                        CPQ_CNEYTaxCalculation taxHandler = new CPQ_CNEYTaxCalculation();
                    	blng__CreditNote__c record = new blng__CreditNote__c(Id = cnRec.Id);
                    	record.blng__Status__c ='Posted';
                    	otherCNList.add(record);
                    }
        }
        update otherCNList;
        
    }
     /**
     * Name : generateDocument
     * Description : Generate A5 document for CreditNote and send email with Doc
     * Param : newList and OldMap
     * Return : None
    
    
    public static void generateDocument(List<blng__CreditNote__c> newList, Map<Id,blng__CreditNote__C> oldMap){
        List<rsdoc__Document_Request__c> listDocRequest = new List<rsdoc__Document_Request__c>();
        
		Map<Id, RecordType> mapRecordType = new Map<Id, RecordType>([select Id,DeveloperName from RecordType where SobjectType ='blng__CreditNote__c']);
        String templateName = 'CreditNote';
        List<rsdoc__Document_Action__c> listDocAction = [SELECT id,rsdoc__Template_Name__c from rsdoc__Document_Action__c where rsdoc__Base_object_API__c = 'blng__CreditNote__c'];
        Map<String, Id > mapCreditNote = new Map<String, Id >();
        for(rsdoc__Document_Action__c action: listDocAction){
        	mapCreditNote.put(action.rsdoc__Template_Name__c,action.Id);   
        }
        System.debug('listDocAction. '+listDocAction);
        if(listDocAction != null && !listDocAction.isEmpty()){
            for(blng__CreditNote__c cnRec : newList){
                System.debug('status . '+cnRec.blng__Status__c );
                System.debug('status . '+oldMap.get(cnRec.Id).blng__Status__c);
                if(cnRec.blng__Status__c == 'Posted' && cnRec.blng__Status__c != oldMap.get(cnRec.Id).blng__Status__c){
                    System.debug('status .inside '+cnRec.blng__Status__c );
                    rsdoc__Document_Request__c docReq = new rsdoc__Document_Request__c();
                    if(mapRecordType.get(cnRec.RecordTypeId)!=null && mapRecordType.get(cnRec.RecordTypeId).DeveloperName!='Master'){
                    	docReq.rsdoc__Document_Action__c  =   mapCreditNote.get('CB '+mapRecordType.get(cnRec.RecordTypeId).DeveloperName);
                    }
                    else{
                    	docReq.rsdoc__Document_Action__c  =  mapCreditNote.get('CreditNote');    
                    }
                    
                    docReq.rsdoc__Record_Id__c = cnRec.Id;
                    docReq.rsdoc__Error_Field__c = 'Doc_Gen_Error__c';
                    listDocRequest.add(docReq);
                }
            }
        }
        System.debug('listDocRequest. '+listDocRequest);
        if(!listDocRequest.isEmpty()&&!(test.isRunningTest())){
            System.debug('insert listDocRequest. '+listDocRequest);
            insert listDocRequest;
        }
    }
    
    /**
     * Name : ValidateCreditAmount
     * Description : Validate The Total Credit Amount of Source Invoice Do Not Exceed the Total Amount
     * Param : newList and OldMap
     * Return : None
     
    public static void ValidateCreditAmount(List<blng__CreditNote__c> newList,Map<Id,blng__CreditNote__c> oldMap){
        Set<Id> noteIds = new Set<Id>();
        for(blng__CreditNote__c cn : newList){
            if(cn.blng__Subtotal__c > 0 &&  oldMap.get(cn.Id).blng__Subtotal__c != cn.blng__Subtotal__c){
                noteIds.add(cn.Id);
            }
        }
        
        if(noteIds.size() > 0 && noteIds != null){
            Map<Id,blng__CreditNote__c> cnInvMap = new Map<Id,blng__CreditNote__c>([SELECT Id,
                                                                                    blng__Subtotal__c,
                                                                                    blng__RelatedInvoice__r.blng__Credits__c,
                                                                                    blng__RelatedInvoice__r.blng__Subtotal__c
                                                                                    FROM blng__CreditNote__c 
                                                                                    WHERE Id IN :noteIds]);
            for(blng__CreditNote__c cn : newList){
                if(cnInvMap.containsKey(cn.Id) && cnInvMap.get(cn.Id).blng__RelatedInvoice__c != null){
                   if(cnInvMap.get(cn.Id).blng__RelatedInvoice__r.blng__Credits__c >= cnInvMap.get(cn.Id).blng__RelatedInvoice__r.blng__Subtotal__c){
                    cn.addError('Cannot Create Credit Notes for Amounts Greate than Invoice Sub Total');
                } 
                }
                
            }
        }
    }
    public static void ValidateCreditAmountInsert(List<blng__CreditNote__c> newList){
        Set<Id> invIds = new Set<Id>();
        for(blng__CreditNote__c cn : newList){
            
                invIds.add(cn.blng__RelatedInvoice__c);
            
        }
        
        if(invIds.size() > 0 && invIds != null){
            Map<Id,blng__Invoice__c> InvMap = new Map<Id,blng__Invoice__c>([SELECT Id,
                                                                            blng__Subtotal__c,
                                                                            blng__Credits__c
                                                                            FROM blng__Invoice__c 
                                                                            WHERE Id IN :invIds]);
            for(blng__CreditNote__c cn : newList){
                if(invMap.containsKey(cn.blng__RelatedInvoice__c) ){
                    if(invMap.get(cn.blng__RelatedInvoice__c).blng__Credits__c >= invMap.get(cn.blng__RelatedInvoice__c).blng__Subtotal__c){
                        cn.addError('Cannot Create Credit Notes for Amounts Greate than Invoice Sub Total');
                    } 
                }
                
            }
        }
    }
    public static void fakemethod(){
        integer i=0;
        i++;
        i++;
   
   
    }
}*/