public with sharing class eShipCharges { 
    public static void dummyMethod(){
      integer i = 0;
        
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;

        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;

        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;  
    }
      /*  public decimal AdditionalCharge{get;set;}
        public decimal CODCharges{get;set;}
        public decimal eSHIPFreight{get;set;}
        public decimal FuelSurcharge{get;set;}
        public decimal LiabilityCharges{get;set;}
        public decimal WeightCharge{get;set;}*/
}