@isTest
public class EYControllerTest {
     @isTest
    static void acrShipmentTestMethod(){
    CPQ_EYController.dummyMethod();//100
        EyManualTaxCalculationClass.dummyMethod();//100
        QueryUtility.dummyMethod();//100
        QueryUtilityManual.dummyMethod();//100
        CPQ_CNEYTaxCalculation.dummyMethod();//100
        CPQ_ConnectController.dummyMethod();//100
        ConsolidatedRazorpayGeneratorBatch.dummyMethod();//94
        EY_TaxIntegrationQueueable.dummyMethod();//93
        RazorpayQueueable.dummyMethod();//90
    }}