public class Indigo_CreateAWBrequest {
    // wrapper class is used to store reponse values 
	public String loginName;
	public String sessionId;
	public String awbPrefix;
	public String origin;
	public String destination;
	public String shippingAgentCode;
	public String commodityCode;
	public String productType;
	public String commodityDesc;
	public String pcs;
	public String grossWt;
	public String chargeableWt;
	public String fltDate;
	public String fltNumber;
	public String UOM;
	public String Dimensions;
	public String ShprAccountCode;
	public String ShprCity;
	public String ShprState;
	public String ShprName;
	public String ShprAdd;
	public String ShprPincode;
	public String ShprCountryCode;
	public String ShprContactNo;
	public String ConsAccountCode;
	public String ConsCity;
	public String ConsState;
	public String ConsName;
	public String ConsAdd;
	public String ConsPincode;
	public String ConsCountryCode;
	public String ConsContactNo;
	public String ScheduleID;
	public String ShprLat;
	public String ShprLong;
	public String ConsLat;
	public String ConsLong;
	public String ShprEmailID;
	public String ConsEmailID;
	public String Unit;
	public String awbNumber;
	public String slac;
	public String dvCustom;
	public String declaredValue;
	public String payMode;
	public String packagingInfo;
	public String TokenNumber;
	public String volume;
	public String shcCode;
	public String multilegRoutes;
    /*
     public static Indigo_CreateAWBrequest parse(String json) {
		return (Indigo_CreateAWBrequest) System.JSON.deserialize(json, Indigo_CreateAWBrequest.class);
	}  */
}