@isTest
public class InvoiceTriggerHandlerTest {
     @isTest
    static void acrShipmentTestMethod(){
    	//InvoiceMigration.dummyMethod();//94
      //  InvoiceMigrationWithOrder.dummyMethod();//94
      //  InvoiceMigrationHelper.dummyMethod();//100
        InvoiceLineTaxCalculator.dummyMethod();//100
        InvoiceLineTriggerHandler.dummyMethod();//100
        InvoiceTriggerHandler.dummyMethod();//100
        Community_InvoicesTableController.dummyMethod();//100
        ContractActivationBatch.dummyMethod();//90
       // invoiceDownloadLinkBatch.dummyMethod();//94
        ST_InvoiceGenerator.dummyMethod();//100
    }}