public class UtilClass {
    public static boolean triggerLoop = false;
    public static boolean recursionCheck = false;
    public static Integer flowSequence = 0;
    public static boolean orderTriggerLoop = false;
    public static boolean qliRecursionCheck = false;
    public static boolean isFirstTime = true;
    public static boolean quoteFirstTime = true;
    public static boolean invLineFirstTime = true;
}